# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'code1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from random import randint
import sys


computerScore = 0
playerScore = 0


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 80, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 80, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 380, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.start)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 380, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.stop)
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 150, 111, 111))
        self.label_3.setStyleSheet("image: url(:/newPrefix/rock.JPG);\n"
"")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/rock.JPG"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 130, 121, 151))
        self.label_4.setStyleSheet("image: url(:/newPrefix/rock.JPG);\n""")

        self.label_4.setText("")
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.Rock_Paper_Scissors = QtWidgets.QMenu(self.menubar)
        self.Rock_Paper_Scissors.setObjectName("Rock_Paper_Scissors")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.Rock_Paper_Scissors.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        
        
        self.timer = QTimer(self)
        self.timer.setInterval(80)
        self.timer.timeout.connect(self.playGame)
    
    def playGame(self):
        self.rndcomputer = randint(1,3)
        self.rndplayer = randint(1,3)
        
        if(self.rndcomputer == 1):
            self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/rock.JPG"))
        elif(self.rndcomputer == 2):
            self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/paper.JPG"))
        else:
            self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/scissors.JPG"))
            
        if(self.rndplayer == 1):
            self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/rock.JPG"))
        elif(self.rndplayer == 2):
            self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/paper.JPG"))
        else:
            self.label_4.setPixmap(QtGui.QPixmap(":/newPrefix/scissors.JPG"))
            
        
            
    
    def start(self):
        self.timer.start()
        
    def stop(self):
        self.timer.stop()
        global computerScore
        global playerScore
        
        if self.rndcomputer == 1 and self.rndplayer == 1:
            mbox = QMessageBox.information(self,"Info","Draw Game")
        
        elif self.rndcomputer == 1 and self.rndplayer == 2:
            mbox = QMessageBox.information(self,"Info","You Win")
            playerScore += 1
            self.label_2.setText("Your Score:{}".format(playerScore))
        
        elif self.rndcomputer == 1 and self.rndplayer == 3:
            mbox = QMessageBox.information(self,"Info","Computer Wins")
            computerScore += 1
            self.label.setText("Computer Score:{}".format(computerScore))
         
        
        elif self.rndcomputer == 2 and self.rndplayer == 1:
            mbox = QMessageBox.information(self,"Info","Computer Wins")
            computerScore += 1
            self.label.setText("Computer Score:{}".format(computerScore))
        
        elif self.rndcomputer == 2 and self.rndplayer == 2:
            mbox = QMessageBox.information(self,"Info","Draw Game")
        
        elif self.rndcomputer == 2 and self.rndplayer == 3:
            mbox = QMessageBox.information(self,"Info","You Win")
            playerScore += 1
            self.label_2.setText("Your Score:{}".format(playerScore))
            
        elif self.rndcomputer == 3 and self.rndplayer == 1:
            mbox = QMessageBox.information(self,"Info","You Win")
            playerScore += 1
            self.label_2.setText("Your Score:{}".format(playerScore))
            
        elif self.rndcomputer == 3 and self.rndplayer == 2:
            mbox = QMessageBox.information(self,"Info","Computer Wins")
            computerScore += 1
            self.label.setText("Computer Score:{}".format(computerScore))
        
            
        elif self.rndcomputer == 3 and self.rndplayer == 3:
            mbox = QMessageBox.information(self,"Info","Draw Game")
        
        
            
        if computerScore == 3 or playerScore == 3:
            mbox = QMessageBox.information(self,"Information","Game Over")
            sys.exit()
        
        
        

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label.setText(_translate("mainWindow", "Computer Score:"))
        self.label_2.setText(_translate("mainWindow", "Your Score:"))
        self.pushButton.setText(_translate("mainWindow", "Start"))
        self.pushButton_2.setText(_translate("mainWindow", "Stop"))
        self.Rock_Paper_Scissors.setTitle(_translate("mainWindow", "Rock Paper Scissors"))
import images_rc

class main(QMainWindow , Ui_mainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setupUi(self)
        

app = QApplication(sys.argv)
window = main()
window.show()
app.exec_()

